### ISSUE TITLE
drf Help Message

### ISSUE THREAD

**Issue by cibersheep** [Utodev/DRC#1]
Running drf with no parameters shows this help message:
```
<define> is a symbol that is automatically defined when compiling. Main use is writing there the target machine, and then add #ifdefs in the code. If you don't understand what that is for, just write any word there, for instance "dummy"

[output.json] is optional file name for output json file, if missing same base name as DSF file will be used.
```

I think they might be:

<define> is an automatically defined symbol at compiling time. Its main use is to be able to target a specific machine adding #ifdefs code blocks for such machine. If you don't understand what it is for, just type any word there, for instance "dummy".

[output.json] is an optional file name for the output json file. If left out, the DSF file base name will be used.

**Comment by Utodev** [comment]
Fixed, will be ready on next build.
