### ISSUE TITLE
Current version bugfixes

### ISSUE THREAD

**Issue by nataliapc** [Utodev/DRC#11]
**File drb.php:**

_line 1317:_
`...$target=!'MSX2'...` => `...$target!='MSX2'...`

_line 701 change to:_
`$condat->NumParams++;` => `$condact->NumParams++;`

**FIXED:**
_line 411 insert new line:_
`$currentOffset++;`

_line 398 insert new line:_
`$message->Text = replaceChars($message->Text);`

**Comment by Utodev** [comment]
Fixed!
