### ISSUE TITLE
XPLAY Tempo bug

### ISSUE THREAD

**Issue by nataliapc** [Utodev/DRC#14]
drb.php:
Lines 1158, 1179 and 1197 must be:

        $condact->Param1 = intval(round($baseLength * (120 / $values[XPLAY_TEMPO]) / $length));

An line 1208 must be:

        $values[XPLAY_TEMPO] = (intval(substr($note, 1)) & 255);

**Comment by Utodev** [comment]
This has long been opened, and it looks like was fixed in a pull request. Please reopen if not.
