### ISSUE TITLE
Compiling Blank Project Warnings

### ISSUE THREAD

**Issue by cibersheep** [Utodev/DRC#2]
DRC alfa 1.2
I have compiled the Blank project for PCW on an Ubuntu 16.04

```
$drf "non" ../../BLANK_ES.DSF 
DAAD Reborn Compiler Frontend 0.1 (C) Uto 2018-2019
Opening ../../BLANK_ES.DSF
[...]
Input file parse completed...
Generating output...
../../BLANK_ES.json generated.
```

That looks ok. Then, 
`$php drb.php pcw es ../BLANK_ES.json` spits these warnings:

https://paste.ubuntu.com/p/mgPKMxxT8H/

**Comment by Utodev** [comment]
There was a bug in a loop which made all those warnings appear. There were no final effects on the DDB, but I have fixed the bug anyway of course.
