### ISSUE TITLE
Feature Request: Additional bank (or banks) of XMESSAGE

### ISSUE THREAD

**Issue by ainslec** [Utodev/DRC#21]
This is separate to my previous (DMESSAGE) issue (which is now closed).

I'd like to ask if it's possible to add for an additional bank (or two) of XMESSAGEs.

There are a number of Adventuron games that are entirely convertible to DAAD, but have too many messages (even with xmessages) and/or too much text (after using all XMESSAGES). Adventuron already moves the largest text strings into XMESSAGES to reduce the RAM burden but it's not enough.

One extra bank will be enough to alleviate the majority of the issues (I could shift another 256 of the larger messages onto storage devices). Two extra banks would be heaven.

This is especially useful for the NEXT as a target, which is my primate DAAD/DRC/MALUVA target from Adventuron.

Thank you for considering this.

**Comment by Utodev** [comment]
For the time being I find this to be complicated, or specifically too much time consuming for the many fronts I have, but I'll think about it.

**Comment by ainslec** [comment]
Thanks Uto. No rush.

DRC is awesome.

**Comment by Utodev** [comment]
Once understood, it seems not to be necessery for the time being, so I'm clossing the issue.
