### ISSUE TITLE
Portuguese characters

### ISSUE THREAD

**Issue by Utodev** [Utodev/DRC#22]
Copied from :https://github.com/daad-adventure-writer/daad/issues/2

According the manual, should be possible mapping special characters using the \ (in DAAD #) character. I saw that á, é, í, ó, ú and ç are already covered. But would be great having some additional accents such as:

#Q ... à
#R ... ã
#S ... õ
#T ... â
#U ... ê
#V ... ô

Thank you very much
Best regards

**Comment by rogeriobiondi** [comment]
Hello,
If you decide to implement this feature, please let me know if I could help with testing and providing the complete list of characters present on the Portuguese Language. I'm also developing an adventure game with DRC, so would be my pleasure helping testing other issues as well.
Muchas gracias
Rogerio

**Comment by Utodev** [comment]
I'm working on it, and adding support for "pt" target to DRC. That means you won't have to care about using #g and #t, the compiler will do it automatically.

I would also need Portuguese compression tokens, what could be obtanined by running DRT  (https://github.com/daad-adventure-writer/DRC) on a large portuguese game. Using Spanish tokens at the moment, but that would produce poor compression for sure.

**Comment by rogeriobiondi** [comment]
Carlos, 
Eliazer and Stefan are doing the translation of Hibernate to Portuguese language. I've talked to Eliazer, who is doing the translation and he he could provide the source code in portuguese language. I also could use my own game, put the accents in the text, download the DRC and generate the .DDB and .json files for testing.

**Comment by Utodev** [comment]
Built in DAAD Ready!
