### ISSUE TITLE
Could README include simple build directions?

### ISSUE THREAD

**Issue by joshgoebel** [Utodev/DRC#25]
Can instructions for building from source also be included in the README?

**Comment by Utodev** [comment]
Hi, the readme says the instructions and download links are in the wiki, and in the wiki you have th build instructions.

https://github.com/daad-adventure-writer/DRC/wiki#BUILDING

**Comment by joshgoebel** [comment]
Indeed.  Thanks.  Might help if the download section referenced building - they are both in the category of "acquiring" in my brain, but I don't think I can edit the wiki. :)

**Comment by Utodev** [comment]
I've slightly updated the README to say the wiki includes usage and build instructions, I hope that helps :-)

**Comment by joshgoebel** [comment]
Maybe that will help.  Dunno.  I'll close though.  I would have considered something like:


```
Find latest version at DRC Releases site, make sure you pick the version with the more recent date.  
You may also choose to [build directly from source](link to #building, etc).
```
