### ISSUE TITLE
[Ubuntu] Undefined function utf8_encode()

### ISSUE THREAD

**Issue by cibersheep** [Utodev/DRC#3]
After install php with `sudo apt install php` I got error:

`Uncaught Error: Call to undefined function utf8_encode() in /home/[...]/drb.php:638`

which can be fixed installing missing components:
`sudo apt install php7.0-xml`

**Comment by Utodev** [comment]
Yes, package php7.0.xml or  generic "php-xml" is required for this software to work., The code will now check  for it and if not will ask the user to install the package, which can be done via:

```
sudo apt install php-xml
yum install php-xml

```
`sudo apt install php7.0-xml` may work as well today, but there will be a time when php8.0 is out, so it's better to use the generic package name.
