### ISSUE TITLE
572:   if ($target=='PCW') return 7;

### ISSUE THREAD

**Issue by cibersheep** [Utodev/DRC#5]
- I took Cozumel dsk that runs on PCW and replaced PARTE001.DDB with the ddb compiled with drb
- Trying to boot the game gives an error: Invalid ¿ddb?
- Changed the line 572 with `if ($target=='PCW') return 7;` and replaced again the PARTE001.DDB 
- Trying to boot the game reboots the emulator (Joyce)

[PARTE001DDB.zip](https://github.com/Utodev/DRC/files/3082455/PARTE001DDB.zip)

**Comment by cibersheep** [comment]
This is the original ddb from Cozumel
[CozumelPCW-parte001ddb.zip](https://github.com/Utodev/DRC/files/3082456/CozumelPCW-parte001ddb.zip)

**Comment by Utodev** [comment]
This issue has been fixed
